program: python -m release_benchmark.cli.train
command:
- ${env}
- python
- -m
- release_benchmark.cli.train
- ${args}
- --method
- randaug
method: grid
metric:
  name: Validation loss
  goal: minimize
parameters:
  lr:
    values:
    - 0.0004
  weight_decay:
    values:
    - 0
  bs:
    values:
    - 256
  epochs:
    values:
    - 100
  optim:
    values:
    - sgd
  pretrain:
    values:
    - 1
  augment:
    values:
    - strong
  seed:
    values:
    - 42
